import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Homepage from './home';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lotto</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className=' bg-[#110E0E] min-h-[100vh] pb-4'>
        <Homepage />
      </main>

    </div>
  );
};

export default Home;
